VACUUM ANALYZE meterprocess.txn_meter_validated_daily;
VACUUM ANALYZE meterprocess.txn_meter_validated_daily_c3mos;
VACUUM ANALYZE meterprocess.txn_meter_validated_daily_h13mos;

VACUUM ANALYZE meterprocess.txn_meter_validated_monthly;
VACUUM ANALYZE meterprocess.txn_meter_validated_monthly_c3mos;
VACUUM ANALYZE meterprocess.txn_meter_validated_monthly_h13mos;

VACUUM ANALYZE meterprocess.txn_meter_raw_mq_daily;
VACUUM ANALYZE meterprocess.txn_meter_raw_mq_daily_c3mos;
VACUUM ANALYZE meterprocess.txn_meter_raw_mq_daily_h13mos;

VACUUM ANALYZE meterprocess.txn_meter_raw_mq_monthly;
VACUUM ANALYZE meterprocess.txn_meter_raw_mq_monthly_c3mos;
VACUUM ANALYZE meterprocess.txn_meter_raw_mq_monthly_h13mos;

VACUUM ANALYZE meterprocess.txn_meter_ssla_mq_daily;
VACUUM ANALYZE meterprocess.txn_meter_ssla_mq_daily_c3mos;
VACUUM ANALYZE meterprocess.txn_meter_ssla_mq_daily_h13mos;

VACUUM ANALYZE meterprocess.txn_meter_ssla_mq_monthly;
VACUUM ANALYZE meterprocess.txn_meter_ssla_mq_monthly_c3mos;
VACUUM ANALYZE meterprocess.txn_meter_ssla_mq_monthly_h13mos;

VACUUM ANALYZE meterprocess.txn_stl_adjusted_monthly;
VACUUM ANALYZE meterprocess.txn_stl_adjusted_monthly_c3mos;
VACUUM ANALYZE meterprocess.txn_stl_adjusted_monthly_h13mos;

VACUUM ANALYZE meterprocess.txn_stl_daily;
VACUUM ANALYZE meterprocess.txn_stl_daily_c3mos;
VACUUM ANALYZE meterprocess.txn_stl_daily_h13mos;

VACUUM ANALYZE meterprocess.txn_stl_final_monthly;
VACUUM ANALYZE meterprocess.txn_stl_final_monthly_c3mos;
VACUUM ANALYZE meterprocess.txn_stl_final_monthly_h13mos;

VACUUM ANALYZE meterprocess.txn_stl_prelim_monthly;
VACUUM ANALYZE meterprocess.txn_stl_prelim_monthly_c3mos;
VACUUM ANALYZE meterprocess.txn_stl_prelim_monthly_h13mos;

VACUUM ANALYZE meterprocess.txn_stl_gesq_adjusted_monthly;
VACUUM ANALYZE meterprocess.txn_stl_gesq_adjusted_monthly_c3mos;
VACUUM ANALYZE meterprocess.txn_stl_gesq_adjusted_monthly_h13mos;

VACUUM ANALYZE meterprocess.txn_stl_gesq_daily;
VACUUM ANALYZE meterprocess.txn_stl_gesq_daily_c3mos;
VACUUM ANALYZE meterprocess.txn_stl_gesq_daily_h13mos;

VACUUM ANALYZE meterprocess.txn_stl_gesq_final_monthly;
VACUUM ANALYZE meterprocess.txn_stl_gesq_final_monthly_c3mos;
VACUUM ANALYZE meterprocess.txn_stl_gesq_final_monthly_h13mos;

VACUUM ANALYZE meterprocess.txn_stl_gesq_prelim_monthly;
VACUUM ANALYZE meterprocess.txn_stl_gesq_prelim_monthly_c3mos;
VACUUM ANALYZE meterprocess.txn_stl_gesq_prelim_monthly_h13mos;

